---
- name: Create and configure rabbitmq container
  hosts: "{{ rabbitmq_host_group | default('rabbitmq_all') }}"
  serial: 1
  gather_facts: "{{ osa_gather_facts | default(True) }}"
  user: root
  tasks:
  - name: extract list of rabbitmq vhosts
    shell: "rabbitmqctl list_vhosts"
    register: RABBITMQ_VHOSTS

  - name: attribute permissions for monitoring user on rabbitmq vhosts
    shell: 'rabbitmqctl set_permissions -p {{ item }} monitoring "^$" ".*" "^$" '
    with_items: "{{ RABBITMQ_VHOSTS.stdout_lines | select('match', '^(/)') | list }}"
