---
# Copyright 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install and configure Collectd
  hosts: "collectd:{{ nova_compute_hosts }}" 
  gather_facts: true
  user: root

  roles:
    - collectd

  post_tasks:
    # Best is to use post tasks to install non default collectd plugins
    - name: Configure Collectd python plugin
      template:
        src: templates/collectd/collectd_python_plugins.conf.j2
        dest: "{{ collectd_plugins_prefix }}/collectd_python_plugins.conf"
        validate: '{{ collectd_sbin_path }}/collectd -t -C %s'
      notify: collectd restart
    - name: Configure OpenStack Check APIs plugins
      template:
        src: templates/collectd/openstack_check_apis.conf.j2
        dest: "{{ collectd_plugins_prefix }}/openstack_check_apis.conf"
        validate: '{{ collectd_sbin_path }}/collectd -t -C %s'
      notify: collectd restart
    - name: Configure OpenStack Compute Stats plugin
      template:
        src: templates/collectd/openstack_compute.conf.j2
        dest: "{{ collectd_plugins_prefix }}/openstack_compute.conf"
        validate: '{{ collectd_sbin_path }}/collectd -t -C %s'
      notify: collectd restart
    - name: Configure OpenStack Cinder Stats plugin
      template:
        src: templates/collectd/openstack_cinder.conf.j2
        dest: "{{ collectd_plugins_prefix }}/openstack_cinder.conf"
        validate: '{{ collectd_sbin_path }}/collectd -t -C %s'
      notify: collectd restart
    - name: Configure OpenStack Glance Stats plugin
      template:
        src: templates/collectd/openstack_glance.conf.j2
        dest: "{{ collectd_plugins_prefix }}/openstack_glance.conf"
        validate: '{{ collectd_sbin_path }}/collectd -t -C %s'
      notify: collectd restart
    - name: Configure OpenStack Keystone Stats plugin
      template:
        src: templates/collectd/openstack_keystone.conf.j2
        dest: "{{ collectd_plugins_prefix }}/openstack_keystone.conf"
        validate: '{{ collectd_sbin_path }}/collectd -t -C %s'
      notify: collectd restart
    - name: Configure OpenStack Keystone Stats plugin
      template:
        src: templates/collectd/openstack_neutron.conf.j2
        dest: "{{ collectd_plugins_prefix }}/openstack_neutron.conf"
        validate: '{{ collectd_sbin_path }}/collectd -t -C %s'
      notify: collectd restart
    - name: Configure OpenStack Nova Stats plugin
      template:
        src: templates/collectd/openstack_nova.conf.j2
        dest: "{{ collectd_plugins_prefix }}/openstack_nova.conf"
        validate: '{{ collectd_sbin_path }}/collectd -t -C %s'
      notify: collectd restart
    - name: Configure Libvirt Collectd plugin
      template:
        src: templates/collectd/libvirt_plugins.conf.j2
        dest: "{{ collectd_plugins_prefix }}/libvirt_plugins.conf"
        validate: '{{ collectd_sbin_path }}/collectd -t -C %s'
      notify: collectd restart
    - name: Configure Libvirt Check plugin
      template:
        src: templates/collectd/libvirt_check_plugins.conf.j2
        dest: "{{ collectd_plugins_prefix }}/libvirt_check_plugins.conf"
        validate: '{{ collectd_sbin_path }}/collectd -t -C %s'
      notify: collectd restart
    - name: Configure Network Collectd plugin
      template:
        src: templates/collectd/network_plugin.conf.j2
        dest: "{{ collectd_plugins_prefix }}/network_plugin.conf"
        validate: "{{ collectd_sbin_path }}/collectd -t -C %s"
      notify: collectd restart
    - name: Copy all python modules
      copy:
        src: files/collectd-modules
        dest: "{{ collectd_plugins_dir }}"
      notify: collectd restart

      tags: [collectd, collectd-plugins]  
    
  handlers:
    - name: collectd restart
      service: name=collectd state=restarted
  
  vars:
    - nova_compute_hosts: "nova_compute:!nova_conductor:!nova_scheduler:!nova_consoleauth:!nova_api_os_compute:!nova_api_placement:!nova_api_metadata:!nova_console"

  vars_files:
    - vars/main.yml
    - vars/collectd.yml
    - vars/influxdb.yml